### PR TITLE
Logger function in options

### PR DESCRIPTION
**Pull request by dottorblaster**
As per #444, I'm implementing a pluggable logger with defaults going to trigger simple console invokes.

I updated tests too, hope this helps!

### CODE REVIEW

**Comment by dottorblaster** [comment]
My bad: I didn't write documentation for this. Should I do that?

**Comment by designfrontier** [comment]
yes please! documentation would be great

**Comment by designfrontier** [comment]
you'll want to pull down the changes I just made to this... I cleaned up some conflicts in the code.

**Comment by designfrontier** [comment]
Code looks great, just waiting on some documentation to get this merged. Thanks so much!

**Comment by dottorblaster** [comment]
@designfrontier just pushed my README updates in https://github.com/ansble/monument/pull/452/commits/fc2fd330dd0d4b58355da0d8d79b8d2c4f875e41, hope this is ok 👍

**Comment by designfrontier** [comment]
Strong Work! This looks fantastic.

**Comment by dottorblaster** [comment]
Thanks!

**Pull request merged**
