### PR TITLE
Expanding router_test.js coverage

### PR DESCRIPTION
**Pull request by RS-Crawford**
Tests written for the compression section of router.js. Found at the bottom of router_test.js under "compression routes."

These tests inadvertently cover the cases where the compressed file doesn't exist since it initially doesn't exist and then gets created after the first test of each type (gzip/deflate) is run. Subsequent tests, therefore, test cases where the file already exists. This happening is not explicitly covered in any language of the tests, though.

Anyway, hope these are what you're looking for!

### CODE REVIEW

**Comment by designfrontier** [comment]
going to try and run through this tonight and hopefully get it merged in the next release

**Comment by designfrontier** [comment]
Refs #195

**Comment by designfrontier** [comment]
Thanks for the contribution! Especially opening the pull request to the correct branch :+1: Above and beyond!

**Comment by RS-Crawford** [comment]
No problem! It was fun. I'll admit, I sweated over the branch for a few minutes... Glad it was useful.

**Comment by designfrontier** [comment]
No need to :sweat: :smile:

**Pull request merged**
